#!/usr/local/bin/python3
#coding: utf-8
# PERSONA

##################################################################################################################################################################
# Created on 21 de Julho de 2021
#
#     Projeto base: nasa
#     Repositorio: stagin gold
#     Author: Maycon Cypriano Batestin
#
##################################################################################################################################################################
##################################################################################################################################################################
# imports

import json
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[1]").appName("local").getOrCreate()

print("Starting processing for gold file...")

###################extrac########################################

nasa = spark.read.parquet("C:/Users/Bates/Documents/Repositorios/BIGDATA/nasa/stagin/silver/nasa/").createOrReplaceTempView("nasa")

###################transform########################################

planet_confirmed = spark.sql("""SELECT
keipID,
koi_name,
kepler_name,
exoplanet_disposition,
vetting_status,
date_of_last_parameter_update,
disposition_using_kepler_data,
disposition_score,
not_transit_like_false_positive_flag,
stellar_eclipse_false_positive_flag,
centroid_offset_false_positive_flag,
ephemeris_math_indicates_contamination_false_positive_flag,
disposition_provenance,
orbital_period_days,
orbital_period_upper_unc_days,
orbital_period_lower_unc_days,
transit_epoch_bkjd,
transit_epoch_upper_unc_bkjd,
transit_epoch_lower_unc_bkjd,
transit_epoch_bjd,
transit_epoch_upper_unc_bjd,
transit_epoch_lower_unc_bjd,
eccentricity,
eccentricity_upper_unc,
eccentricity_lower_unc,
long_periastron_deg,
long_periastron_upper_unc_deg,
long_periastron_lower_unc_deg,
impact_parameter,
impact_parameter_upper_unc,
impact_parameter_lower_unc,
transit_duration_hrs,
transit_duration_upper_unc_hrs,
transit_duration_lower_unc_hrs,
ingress_duration_hrs,
ingress_duration_upper_unc,
ingress_duration_lower_unc,
transit_depth_ppm,
transit_depth_upper_unc_ppm,
transit_depth_lower_unc_ppm,
planet_star_radios_ratio,
planet_star_radius_ratio_upper_unc,
planet_star_radius_ratio_lower_unc,
fitted_stellar_density,
fitted_stellar_density_upper_unc_gcm3,
fitted_stellar_density_lower_unc_gcm3,
planetary_fit_type,
planetary_radius_earth_radii,
planetary_radius_upper_unc_earth_raddi,
planetary_radius_lower_unc_earth_raddi,
orbit_semi_major_axis_au,
orbit_semi_major_axis_upper_unc_au,
orbit_semi_major_axis_lower_unc_au,
inclination_deg,
inclination_upper_unc_deg,
inclination_lower_unc_deg,
equilibrium_temperature_k,
equilibrium_temperature_upper_unc_k,
equilibrium_temperature_lower_unc_k,
isolation_flux,
isolotaion_flux_upper_unc,
isolation_flux_lower_unc,
planet_star_distance_over_star_radius,
planet_star_distance_over_star_radius_upper,
planet_star_distance_over_star_radius_lower,
limb_darkening_model,
limb_darkening_coeff_4,
limb_darkening_coeff_3,
limb_darkening_coeff_2,
limb_darkening_coeff_1,
parameters_provenance,
maximum_single_event_statistic,
maximum_multiple_event_statistic,
transit_signal_to_noise,
number_of_planets,
number_of_transits,
tce_planet_number,
tce_delivery,
quarters,
odd_even_depth_comparision_statistic,
transit_model,
degress_of_freedom,
chi_square,
link_to_dv_report,
link_to_dv_summary,
stellar_effective_temperature_k,
stellar_effective_temperature_upper_unc_k,
stellar_effective_temperature_lower_unc_k,
stellar_surface_gravity,
stellar_surface_gravity_upper_unc,
stellar_surface_gravity_lower_unc,
stellar_metallicity_dex,
stellar_metallicity_upper_unc,
stellar_metallicity_lower_unc,
stellar_radius_solar_raddi,
stellar_radius_upper_unc_solar_raddi,
stellar_radius_lower_unc_solar_raddi,
stellar_mass_solar_mass,
stellar_mass_upper_unc_solar_mass,
stellar_mass_lower_unc_solar_mass,
stellar_age_gyr,
stellar_age_upper_unc_gyr,
stellar_age_lower_unc_gyr,
stellar_parameter_provenance,
ra,
dec,
kepler_band,
g_band,
r_band,
i_band,
z_band,
j_band,
h_band,
k_band,
yearmonthday
FROM nasa
WHERE not_transit_like_false_positive_flag = 0 and stellar_eclipse_false_positive_flag = 0 and  centroid_offset_false_positive_flag = 0 and ephemeris_math_indicates_contamination_false_positive_flag = 0
""")

nasa = spark.sql("""SELECT
keipID,
koi_name,
kepler_name,
exoplanet_disposition,
vetting_status,
date_of_last_parameter_update,
disposition_using_kepler_data,
disposition_score,
not_transit_like_false_positive_flag,
stellar_eclipse_false_positive_flag,
centroid_offset_false_positive_flag,
ephemeris_math_indicates_contamination_false_positive_flag,
disposition_provenance,
orbital_period_days,
orbital_period_upper_unc_days,
orbital_period_lower_unc_days,
transit_epoch_bkjd,
transit_epoch_upper_unc_bkjd,
transit_epoch_lower_unc_bkjd,
transit_epoch_bjd,
transit_epoch_upper_unc_bjd,
transit_epoch_lower_unc_bjd,
eccentricity,
eccentricity_upper_unc,
eccentricity_lower_unc,
long_periastron_deg,
long_periastron_upper_unc_deg,
long_periastron_lower_unc_deg,
impact_parameter,
impact_parameter_upper_unc,
impact_parameter_lower_unc,
transit_duration_hrs,
transit_duration_upper_unc_hrs,
transit_duration_lower_unc_hrs,
ingress_duration_hrs,
ingress_duration_upper_unc,
ingress_duration_lower_unc,
transit_depth_ppm,
transit_depth_upper_unc_ppm,
transit_depth_lower_unc_ppm,
planet_star_radios_ratio,
planet_star_radius_ratio_upper_unc,
planet_star_radius_ratio_lower_unc,
fitted_stellar_density,
fitted_stellar_density_upper_unc_gcm3,
fitted_stellar_density_lower_unc_gcm3,
planetary_fit_type,
planetary_radius_earth_radii,
planetary_radius_upper_unc_earth_raddi,
planetary_radius_lower_unc_earth_raddi,
orbit_semi_major_axis_au,
orbit_semi_major_axis_upper_unc_au,
orbit_semi_major_axis_lower_unc_au,
inclination_deg,
inclination_upper_unc_deg,
inclination_lower_unc_deg,
equilibrium_temperature_k,
equilibrium_temperature_upper_unc_k,
equilibrium_temperature_lower_unc_k,
isolation_flux,
isolotaion_flux_upper_unc,
isolation_flux_lower_unc,
planet_star_distance_over_star_radius,
planet_star_distance_over_star_radius_upper,
planet_star_distance_over_star_radius_lower,
limb_darkening_model,
limb_darkening_coeff_4,
limb_darkening_coeff_3,
limb_darkening_coeff_2,
limb_darkening_coeff_1,
parameters_provenance,
maximum_single_event_statistic,
maximum_multiple_event_statistic,
transit_signal_to_noise,
number_of_planets,
number_of_transits,
tce_planet_number,
tce_delivery,
quarters,
odd_even_depth_comparision_statistic,
transit_model,
degress_of_freedom,
chi_square,
link_to_dv_report,
link_to_dv_summary,
stellar_effective_temperature_k,
stellar_effective_temperature_upper_unc_k,
stellar_effective_temperature_lower_unc_k,
stellar_surface_gravity,
stellar_surface_gravity_upper_unc,
stellar_surface_gravity_lower_unc,
stellar_metallicity_dex,
stellar_metallicity_upper_unc,
stellar_metallicity_lower_unc,
stellar_radius_solar_raddi,
stellar_radius_upper_unc_solar_raddi,
stellar_radius_lower_unc_solar_raddi,
stellar_mass_solar_mass,
stellar_mass_upper_unc_solar_mass,
stellar_mass_lower_unc_solar_mass,
stellar_age_gyr,
stellar_age_upper_unc_gyr,
stellar_age_lower_unc_gyr,
stellar_parameter_provenance,
ra,
dec,
kepler_band,
g_band,
r_band,
i_band,
z_band,
j_band,
h_band,
k_band,
yearmonthday
FROM nasa
WHERE not_transit_like_false_positive_flag != 0 and stellar_eclipse_false_positive_flag != 0 and  centroid_offset_false_positive_flag != 0 and ephemeris_math_indicates_contamination_false_positive_flag != 0
""")

###################load########################################

nasa.write.mode("overwrite").format("parquet").partitionBy("yearmonthday").save("C:/Users/Bates/Documents/Repositorios/BIGDATA/nasa/stagin/gold/nasa_full")
planet_confirmed.write.mode("overwrite").format("parquet").partitionBy("yearmonthday").save("C:/Users/Bates/Documents/Repositorios/BIGDATA/nasa/stagin/gold/planets_confirmed")
